// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rlbfgs_optim
vec rlbfgs_optim(vec q1, vec q2, vec time, int maxiter, double lam, int penalty);
RcppExport SEXP _fdasrvf_rlbfgs_optim(SEXP q1SEXP, SEXP q2SEXP, SEXP timeSEXP, SEXP maxiterSEXP, SEXP lamSEXP, SEXP penaltySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< vec >::type q1(q1SEXP);
    Rcpp::traits::input_parameter< vec >::type q2(q2SEXP);
    Rcpp::traits::input_parameter< vec >::type time(timeSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type lam(lamSEXP);
    Rcpp::traits::input_parameter< int >::type penalty(penaltySEXP);
    rcpp_result_gen = Rcpp::wrap(rlbfgs_optim(q1, q2, time, maxiter, lam, penalty));
    return rcpp_result_gen;
END_RCPP
}
