# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rlbfgs_optim <- function(q1, q2, time, maxiter = 30L, lam = 0.0, penalty = 0L) {
    .Call(`_fdasrvf_rlbfgs_optim`, q1, q2, time, maxiter, lam, penalty)
}

