# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dpcode <- function(q1, q1L, q2L, times, cut) {
    .Call(`_fdasrvf_dpcode`, q1, q1L, q2L, times, cut)
}

simucode <- function(iter, p, qt1_5, qt2_5, L, tau, times, kappa, alpha, beta, powera, dist, dist_min, best_match, match, thin, cut) {
    .Call(`_fdasrvf_simucode`, iter, p, qt1_5, qt2_5, L, tau, times, kappa, alpha, beta, powera, dist, dist_min, best_match, match, thin, cut)
}

itercode <- function(iter, n, m, mu_5, match_matrix, qt_matrix, qt_fitted_matrix, L, tau, times, kappa, alpha, beta, powera, best_vec, dist_vec, best_match_matrix, mu_prior, var_const, sumdist, thin, mu_q, mu_q_standard, logmax, burnin, AVG) {
    .Call(`_fdasrvf_itercode`, iter, n, m, mu_5, match_matrix, qt_matrix, qt_fitted_matrix, L, tau, times, kappa, alpha, beta, powera, best_vec, dist_vec, best_match_matrix, mu_prior, var_const, sumdist, thin, mu_q, mu_q_standard, logmax, burnin, AVG)
}

calcY <- function(area, gy) {
    .Call(`_fdasrvf_calcY`, area, gy)
}

cuL2norm2 <- function(x, y) {
    .Call(`_fdasrvf_cuL2norm2`, x, y)
}

trapzCpp <- function(x, y) {
    .Call(`_fdasrvf_trapzCpp`, x, y)
}

order_l2norm <- function(x, y) {
    .Call(`_fdasrvf_order_l2norm`, x, y)
}

find_grad_2D <- function(dfdu, dfdv, f, n, t, d) {
    .Call(`_fdasrvf_find_grad_2D`, dfdu, dfdv, f, n, t, d)
}

check_cross <- function(f, n, t, D) {
    .Call(`_fdasrvf_check_cross`, f, n, t, D)
}

find_phistar <- function(w, q, b, n, t, d, K) {
    .Call(`_fdasrvf_find_phistar`, w, q, b, n, t, d, K)
}

mlogit_warp_grad_wrap <- function(m1, m2, alpha, beta, ti, gami, q, y, max_itri, toli, deltai, displayi) {
    .Call(`_fdasrvf_mlogit_warp_grad_wrap`, m1, m2, alpha, beta, ti, gami, q, y, max_itri, toli, deltai, displayi)
}

DPQ2 <- function(Q1, T1, Q2, T2, m1, n1, n2, tv1, tv2, n1v, n2v, lam1, nbhd_dim) {
    .Call(`_fdasrvf_DPQ2`, Q1, T1, Q2, T2, m1, n1, n2, tv1, tv2, n1v, n2v, lam1, nbhd_dim)
}

DPQ <- function(Q1, Q2, n1, N1, lam1, pen1, Disp) {
    .Call(`_fdasrvf_DPQ`, Q1, Q2, n1, N1, lam1, pen1, Disp)
}

rlbfgs <- function(q1, q2, time, maxiter, lam, penalty) {
    .Call(`_fdasrvf_rlbfgs`, q1, q2, time, maxiter, lam, penalty)
}

